[project]
name = "simnibs"
version = "0.1.0"
description = "Simulation of Non-Invasive Brain Stimulation"
readme = "README.md"
requires-python = "3.11.*"
license = { text = "GPL-3.0-only" }
authors = [
  { name = "SimNIBS developers", email = "support@simnibs.org" }
]
maintainers = []
dependencies = [
  # 3D 快速多极子方法（Fast Multipole Method, FMM）Python 接口
  "fmm3dpy==1.0.0",
  "h5py",
  "jsonschema",
  "nibabel",
  "numba",
  "numpy",
  # PETSc 的 Python 接口（并行线性代数求解器）
  "petsc4py",
  "pillow",
  # 生成高斯点/权重（Gauss–Patterson / Gaussian quadrature）
  "pygpc==0.4.1",
  "requests",
  # MRI 分割工具（SAMSEG）
  "samseg",
  "scipy",
  "mkl; sys_platform != 'darwin'",
  "tbb; sys_platform != 'darwin'",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pytest = "*"
mock = "*"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
